### ISSUE TITLE
[WIP] Blinnikova lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#16]
To @JoolsBlinnikova 

1. В программах на Си и Паскале не надо учитывать ; в объявлениях переменных, поскольку и сами объявления Вы не учитываете. Точнее, не должны: например, tol в первый раз не учитывается, т.е. количество данного операнда 3, а не 4. Для паскаля -- аналогично.

2. Далее, с ассемблером: Вы не должны учитывать вхождение операндов в адресацию. Поясню: Вы насчитали 102 вхождения rbp, но при этом само по себе использование регистра происходит всего 8 раз, все остальные -- в адресации, которые при этом Вы считаете как отдельные операнды. 

3. Не очень понятен потенциальный результат. Чтобы было очевидней, требуется писать то критическое коли-во операндов n2, которые Вы используете. В данном случе в методе симпсона у Вас n2 = 4 : 2 границы, эпсилон и сумма. Это нужно уточнить.

4. Количество ошибок не может быть дробным числом. Округляйте это значение ввех до целого.

**Comment by JoolsBlinnikova** [comment]
Замечания учтены.
Файл добавлен https://github.com/JAkutenshi/metrology2020/pull/21

**Comment by JAkutenshi** [comment]
Все верно, но n2* у Вас там по прежнему через 5 считалось. Смержу с 5й работой, пока поправьте этот ньюанс

**Comment by JoolsBlinnikova** [comment]
У меня в работе считается через 4 : 2 границы, эпсилон и сумма.
![image](https://user-images.githubusercontent.com/22082462/79633873-e4e83e80-816f-11ea-930b-a991636e582b.png)

**Comment by JAkutenshi** [comment]
Ну, я мотрю работу в ветке JoolsBlinnikova:blinnikova:
![Screenshot from 2020-04-18 16-06-52](https://user-images.githubusercontent.com/7635910/79638566-bb8adb00-818e-11ea-9d2d-c0e7955fdf7d.png)
V* = 19.65  Вы можете получить только с n2* = 5

**Comment by JoolsBlinnikova** [comment]
Исправлено https://github.com/JAkutenshi/metrology2020/pull/101

**Comment by JAkutenshi** [comment]
Принято
