### ISSUE TITLE
[WIP] Grigoriev lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#17]
To @contentm4ker

1. С ассемблером что-то не ладно: в операторы закрались численные литералы, а в операндах нету токенов с адресацией. Подозреваю, что числа как раз оттуда. Требуется токены с адресацией, например -24(%rbp) считать как за единый целый операнд. И надо отметить, что %rbp отдельно, а -24(%rbp) -- отдельно, т.е. число вхождений rbp как операнда не учитывает его присутствие в адресациях. Т.е. rbp в Вашем случае появляется 7 раз, а -24(%rbp) == 3. Такая же история с %rip: чтобы его непосредственно изменять нужно несоклько извращаться, компилятор такое, насколько я знаю, не делает. В Вашем случае rip работает вместе с дополнительными элементами вроде смещениями до меток, а сам по себе как операнд не учавствует.

2. По программе на Си: у Вас sum не инициализируется, насколько я знаю там может быть любое значение и в итоге алгоритм будет работать некорректно. Стоит добавить строчку инициализации.

3. Уточните минимальное возможное количество операндов n2* при подсчете потенциального объема V*, у меня результат не сходится (Потенциальный объем программы        V* =  15.509775004326936) Как следствие требуется пересчитать остальное, зависящее от V*

4. Объявления переменных не учитываются в подсчетах. Т.е. токены типов (int, void итд) не являются операторами. 

5. Количество начальных ошибок B -- целое число, так что округляйте вверх до целого.

**Comment by contentm4ker** [comment]
#25

**Comment by JAkutenshi** [comment]
Принято
