### ISSUE TITLE
[ACCEPT] Ivankova lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#18]
To @valeriaivankova98

1. По автоматическому посчету токенов и метрик паскаля и си так же нужно сделать таблицу, желательно сводную с соответствующими ручными подсчетами, чтобы можно было сравнить.

2. writeln и printf не учитываются (см. методические указания) как и любой вывод на экран, ибо в данной работе рассатривается именно вычислительный алгоритм. Подозреваю, что вся функция write_arr не нужна.

3. У Вас весьма грубое округление в процессе вычислений. Это очень заметно на вычислении работы программиста. Если считать с большей точностью, то 
```
V = 708.4856577255372 
L = 0.016386556803009145
E = V / L == 43235.785665200536 
```
Разница между Вашим значением и более точным 1045.4643347994643 , что заметно и значительно 

4. Так же непонятно откуда такое время кодирования 
```
T = (n1 * N2 * N * log2(n)) / (2 * S * n2)
```
При S = 10 больше 1000

5. Количество ошибок -- целое число, нужно Ваше значение округлить вверх. Стоит отметить, что после пересчета от всего вышесказанного, у нас появляется разница: у Вас B == 2, у меня -- 1.

**Comment by valeriaivankova98** [comment]
Все указанные замечания исправила. Файл добавила #34

**Comment by JAkutenshi** [comment]
Принято
