### ISSUE TITLE
[WIP] Zil lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#20]
To @SiarheiZyl

1. esp eax и edx не сходится количество не сходится. esp == 9 eax == 71 esp == 9 . Есть подозрение, что адресациб по регистру, (%esp) например вы посчитали как регистр, а не отдельный токен, но это тоже не совсем сходится, ибо их там 7 штук и 9 + 7 != 12. В общем, там что-то не так.

2. Как у Вас считается время кодирования? 

3. Уровень ошибок == первоначальное теоретическое кол-во ошибок и должно быть целым числом. Окрегляйте в большую сторону.

**Comment by SiarheiZyl** [comment]
1. Исправил, выделил в отчете жирным шрифтом
2. T=E/S, где S - число Страуда(в материалах написано принимать равным 10)
3. Исправил, выделил в отчете жирным шрифтом

**Comment by JAkutenshi** [comment]
Принято
