### ISSUE TITLE
[WIP] Koritov lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#43]
@SqrtMinusOne

1. Уровень программы не может быть 0, увеличьте количество знаков после запятой.
2. Какое минимальное кол-во операндов n2* Вы взяли и почему?
3. Число ошибок B у Вас многовато получается. Как Вы считали?
4. Как-то слишком мало операторов movq. Уточните это. Movl и leaq -- тоже. Можно это просто проверить поиском по Вашему отчету, для простоты leaq: у Вас их всего 10, а в отчете 27 не считая последнего вхождения из таблицы, что сходится с моим анализом.
5. Отдельно выделю call: у Вас во-первых почему-то по меткам разделяется, это один оператор и операндом у него cs:ip или ip. Разделить их можно по этому методу (ближний или дальний вызов), но разрешается закрыть на это глаза и считать все call-ы, даже внешних функций. И их больше.
5. Подсчет адресации подразумевается иначе: вся конструкция адресации считается операндом. Пример: leaq 0(,%rdx,8), %rcx тут оператор leaq, и два разных операнда 0(,%rdx,8) и %rcx. Из этого факта есть следствия: числовые константы (0, -4 итд) не могут быть операторами, а так же %rcx как отдельный оператор и внутри адресации -- разные вещи и считаются по разному. Следовательно вхождение регистров требуется пересчитать, в частности %rbp там в районе 20 штук, а все остальное -- вхождения. Как понимаете, все расчеты по программе будут сильно иные.
6. Не очень понял как считался ручной рассчет программ на Си и Паскале. Пример: у Вас посчитано только 3 цикла for, их мягко говоря больше. Уточните это так же.

**Comment by SqrtMinusOne** [comment]
По вопросам:
2. Брал `η_2^* = 3`. Решается задача **Ax** = **b**, дано **A**, **b**, надо найти **x** - 3 операнда.
3. Число ошибок брал:
```python
B = V / 400
```
Логику за этим решением восстановить уже не могу. Это неверно?
4, 7. В указаниях сказано исключить из расчёта процедуры ввода-вывода, что я и попытался сделать. Непосредственно в ходе расчёта используются:
* Pascal - строчки 89, 99, 100
* C - строчки 57, 69, 70.
Таким же образом поступил с ассемблером - собрал ассемблерный код с информацией о соответствии фрагментов C и ассемблера и исключил из ассемблерного кода те фрагменты, которые соответствуют исключенным фрагментам на C. 

По той же причине call у меня меньше.

**Comment by JAkutenshi** [comment]
2. Принято.
3. Формула следующая:
```
B = (V*)^2 / (1000 * λ)
```
V* -- потенциальный объем, а λ -- уровень языка.

Про ввод-вывод понял, тогда лучше было вставить актуальный код для рассчета х_х 

Допустим тогда исправляйте 1 и 3. Учтите, что кол-во ошибок -- это целое число, округляйте в большую сторону.

**Comment by SqrtMinusOne** [comment]
Исправил, #49.

**Comment by JAkutenshi** [comment]
Принято
