### ISSUE TITLE
[WIP] Piskunov lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#45]
@ierikhon

1. Как Вы выбирали минимальное кол-во операндов n2*? Стоит отметить, что при рассчете потенциального объема мы хотим некий идеальный и очень высокоуровневый язык, в котором у нас есть всевозможные функции (поэтому и 2 оператора -- присваивание и функция сделать_все), а так же максимальный уровень абстракции данных. Т.е. с массивами мы обходимся не как 3х3 множество отдельных чисел, а как с единой сущностью. Учтите это в работе.
2. В теоретическом времени разработки в Паскале у Вас, кажется, запятая на один разряд не там.
3. Количество ошибок -- число целое. Округлите в большую сторону.

**Comment by ierikhon** [comment]
1. Учитывая указанное, n2* = 2, так как имеется один входной параметр (матрица, представляющая систему уравнений) и один выходной (вектор решений). Все метрики пересчитаны согласно этому значению
2. Там не хватало двойки в начале, теперь там иное значение из-за п. 1.
3. Исправлено

#53

**Comment by JAkutenshi** [comment]
Принято
