### ISSUE TITLE
[WIP] Ryibin lab1

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#48]
1. При подсчете регистров, например rbp, не учитываются их вхождения в адресацию. Только как самостоятельного токена.
2. На языках Си и Паскаль объявления не учитываются, т.к. это информация компилятору и не перходят в исполняемый код. Ни операнды, ни операторы (;)
3. Какое минимальное кол-во операндов n2* Вы взяли и почему?
4. Число ошибок не может быть вещественным числом.

**Comment by AleksandrRybin** [comment]
fix PR #91 

Взял равным **5** потому что:

1. массив x (входной параметр)
2. массив y (входной параметр)
3. длина массивов (входной параметр)
4. коэффицент наклона линеаризующей прямой (выходной параметр)
5. свободный коэффицент линеаризующей прямой (выходной параметр)

**Comment by JAkutenshi** [comment]
1. Я наверное не до конца уточнил, извиняюсь. Да, rbp отдельно посчитали, но удалять адресации не надо было. Просто они считаются как отдельные операнды. Пример:
```
DWORD PTR [rbp-28]
[0+rax*4]
QWORD PTR [rbp-56]
```
Это три разных операнда. 

2. Ну, Вы убрали main и сказать насколько верно теперь у Вас подсчет не могу. Предположительно нет, ибо парсер подсчитывает и в объявлениях, и в Си у Вас совпали значения с парсером.  Ну, допустим, это не самая важная проблема.

3. Рассчеты теперь примерно сходятся (кроме времени программирования, судя по всему считалось по другой формуле)

4. Количество ошибок не может быть нулем, округление идет в сторону увеличения всегда. В любой программе потенциально есть хотя бы одна ошибка.

**Comment by JAkutenshi** [comment]
Да, но адресации-то убирать не надо было! Верните их как операнды и пересчитайте по ассемблеру метрики. И все.

**Comment by JAkutenshi** [comment]
Принято
