### ISSUE TITLE
[ACCEPT] Ivanov lab2

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#75]
@Citronnn 

1. В заданном в первой части графе дуга не 3-11, а 11-3, это цикл. Соответственно никаких ветвлений с 3мя дугами нету. Если бы даже в теории там был свич, то все равно придется пройтись по всем дугам и этот узел почитается там, т.е. принимать узел 3 за 2 единицы неправильно. Ну а в текущей ситуации это цикл, нужно пересчитать оба способа.

2. Замечание, а не ошибка: в анализе программы узлов 11 и 20 не должно быть, поскольку нету блока else, но структурно оно не влияет на рассчеты. Просто чтобы иметь ввиду.

Все остальное верно

**Comment by Citronnn** [comment]
В файле с вариантами направление дуги не было указано, поэтому я выбрал то, которое принимает программа, т.е. 3-11. Залил сейчас версию, в которой взято приближение к исходному варианту, но вместо дуги 11-3 - дуга 11-8.

**Comment by JAkutenshi** [comment]
Принято
