### ISSUE TITLE
[ACCEPT] Koritov lab2

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#77]
@SqrtMinusOne 

1. В рассчете данного графа вторым способом Вы в первом циклическом маршруте получили 2 узла, а не 1 (11, из 7 выходит одна дуга). Поправьте.

2. Не понятно что там в программе не так и зачем нужна 16я вершина? 

3. Преобразование программы в граф не очевидное. 

TL;DR: Вам либо упрощать программу, убирая весь ввод-вывод и прочее управление памятью, которое к алгоритму особо не относится, либо четко и с пояснениями делать структуру графа по-честному.

Я набросал схему, например:
![photo_2020-04-13_23-14-32](https://user-images.githubusercontent.com/7635910/79157067-9556eb00-7ddc-11ea-9be8-5368c1339d51.jpg)

Я попытался разобрать Вашу схему, из того, что заметил, это непонятный цикл 13-14, между get_data и print_matr нету никаких одинарных циклов, а эти функции имеют каждый по вложенному. Далее связь совсем теряется. Узлы 20 .. 26 выглядят как цикл тройной вложенности, но там такого нет. solve начинается со вложенных циклов, потом не учтен ненулевой определитель, ибо если он равен нулю, то setup-ы не выолняются. Далее, 3 _подряд_ выполняющихся сетапа из цикла и вложенного if с циклом очистки массива в конце.
И брейка нету вообще на Вашем графе. 

Исправляйте

**Comment by SqrtMinusOne** [comment]
По 2: методом бисекции по графу получилось, что вот этот участок:
```
+--+                     +--+
|9 |                     |7 +<-----+
++-+                     +-++      |
 |                         |       |
 |                         |       |
 |                         |       |
 |                         |       |
 |                         |       |
 |                         v       |
 |                       +-++      |
 +---------------------->+11+------+
                         +--+
```
кладет программу. 

А вот так всё нормально:
```
+--+                     +--+
|9 |                     |7 +<-----+
++-+                     +-++      |
 |                         |       |
 |                         |       |
 |                         |       |
 |                         |       |
 |                         |       |
 |                         v       |
 |                       +-++      |
 |                       |11+------+
 |                       ++-+
 |                        |
 |                        v
 |                       ++-+
 +---------------------->+16|
                         +--+
```

**Comment by SqrtMinusOne** [comment]
Поправил 1, сделал граф поаккуратнее.
#102

**Comment by JAkutenshi** [comment]
Приянто
