### ISSUE TITLE
[ACCEPT] Rybin lab2

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#78]
@AleksandrRybin

1. При расчете данного графа первым способом не учтена ни в одном маршруте дуга 5-7, вот и вычисления неверные. В сравнении сказать, что "ну, просто маршруты разные" не считается, это не просто так предлагается сделать, нашли бы ошибку.

2. Описание для ways у Вас неверное, нету дуги 8-10, конечно же решение у него будет несоклько иным.

3. Цикломатическое число посчитано неверно, пересчитывайте составлящие. При расчете этим способом у Вас каким-то чудесным образом исчез независимый цикл, а число маршрутов совпало с Z -- такого не бывает.

4. При составлении структурного графа во второй части работы условие цикла не разбивается на части, а рассматривается как его начало + линейный блок после. В противном случае, в Вашей схеме дублируется сравнение  i < n, чего ,конечно же, структурн оне происходит, сравнение выполняется всегда перед циклом. Упростите граф и пересчитайте сложности.

**Comment by JAkutenshi** [comment]
@AleksandrRybin Вопросы все еще актуальны!

**Comment by AleksandrRybin** [comment]
1-3 Поправил.

4. Первое сравнение, например в вершине 3, выполняется ровно один раз перед входом в цикл  на первой итерации, а далее следует тело цикла, инкремент счётчика и следующая проверка условия уже в другой вершине. Аналогично в вершинах 8-12. Это сделано так, потому что в том виде, про который Вы пишите программа для анализа граф не воспринимает. Прикладываю изображение изначального графа, который программа не воспринимает.
![linfit_error](https://user-images.githubusercontent.com/21968465/79836318-abeeda80-83b8-11ea-9982-4523a7bedefb.jpg)

**Comment by JAkutenshi** [comment]
Принято
