### ISSUE TITLE
[WIP] Zil lab2

### ISSUE THREAD

**Issue by JAkutenshi** [JAkutenshi/metrology2020#79]
Не очень понятна структура графа по Вашей программе. Например, узел 2 -- это что? если дабл перед циклом, то он не может никак перескочить цикл по ребру 2-4. У Вас же уже сделана 4я лаба, там в методичке указано как вот прям правильно отображать каждый из циклов. Требуется поправить граф, желательно указав  и пересчитать его сложность.

**Comment by SiarheiZyl** [comment]
#94 - готово

**Comment by JAkutenshi** [comment]
А что-такое узлы 7 и 8? Я не вижу явного if-а. Есть догадки, но лучше уточните Вы.

**Comment by SiarheiZyl** [comment]
Если MAX==0, то функция sort1 не сработает и состоится переход к функции sort2. Одна итерация оператора do..while произойдет в функции sort2 при MAX==0.

**Comment by JAkutenshi** [comment]
Не совсем это правильно, но принято
